((((lambda (f)
    ((lambda (x) (f (lambda (v) ((x x) v))))
       (lambda (x) (f (lambda (v) ((x x) v))))))
         (lambda (fast_pow)
           (lambda (a)
             (lambda (b)
               (cond ((< b 1) 1)
                 (else (cond ((< b 2) a)
                         (else (* ((fast_pow a)
                                     (/ b 2))
                                  ((fast_pow a)
                                     (/ (+ b 1) 2)) ))))))))
) 2) 0)

((((lambda (f)
    ((lambda (x) (f (lambda (v) ((x x) v))))
       (lambda (x) (f (lambda (v) ((x x) v))))))
         (lambda (fast_pow)
           (lambda (a)
             (lambda (b)
               (cond ((< b 1) 1)
                 (else (cond ((< b 2) a)
                         (else (* ((fast_pow a)
                                     (/ b 2))
                                  ((fast_pow a)
                                     (/ (+ b 1) 2)) ))))))))
) 2) 5)
